short_name: AddictO
full_name: addicto-org/addiction-ontology
release_file: addicto.owl
release_script_path: addicto.release.json
id_digits: 7
indexed_files:
- inputs/.*\.xlsx
main_branch: master
prefixes:
  ADDICTO: http://addictovocab.org/ADDICTO_
  APOLLO_SV: http://purl.obolibrary.org/obo/APOLLO_SV_
  BCIO: http://humanbehaviourchange.org/ontology/BCIO_
  BFO: http://purl.obolibrary.org/obo/BFO_
  CHEBI: http://purl.obolibrary.org/obo/CHEBI_
  CHMO: http://purl.obolibrary.org/obo/CHMO_
  CMO: http://purl.obolibrary.org/obo/CMO_
  COB: http://purl.obolibrary.org/obo/COB_
  DOID: http://purl.obolibrary.org/obo/DOID_
  EFO: http://www.ebi.ac.uk/efo/EFO_
  ENVO: http://purl.obolibrary.org/obo/ENVO_
  ERO: http://purl.obolibrary.org/obo/ERO_
  GAZ: http://purl.obolibrary.org/obo/GAZ_
  GMHO: https://galenos.org.uk/ontologies/GMHO_
  GO: http://purl.obolibrary.org/obo/GO_
  GSSO: http://purl.obolibrary.org/obo/GSSO_
  HP: http://purl.obolibrary.org/obo/HP_
  IAO: http://purl.obolibrary.org/obo/IAO_
  MF: http://purl.obolibrary.org/obo/MF_
  MFOEM: http://purl.obolibrary.org/obo/MFOEM_
  NCIT: http://purl.obolibrary.org/obo/NCIT_
  OAE: http://purl.obolibrary.org/obo/OAE_
  OBCS: http://purl.obolibrary.org/obo/OBCS_
  OBI: http://purl.obolibrary.org/obo/OBI_
  OGMS: http://purl.obolibrary.org/obo/OGMS_
  OMIABIS: http://purl.obolibrary.org/obo/OMIABIS_
  OMRSE: http://purl.obolibrary.org/obo/OMRSE_
  OPMI: http://purl.obolibrary.org/obo/OPMI_
  PATO: http://purl.obolibrary.org/obo/PATO_
  PDRO: http://purl.obolibrary.org/obo/PDRO_
  PO: http://purl.obolibrary.org/obo/PO_
  PR: http://purl.obolibrary.org/obo/PR_
  RO: http://purl.obolibrary.org/obo/RO_
  SDGIO: http://purl.unep.org/sdg/SDGIO_
  SEPIO: http://purl.obolibrary.org/obo/SEPIO_
  SIO: http://semanticscience.org/resource/SIO_
  STATO: http://purl.obolibrary.org/obo/STATO_
  UBERON: http://purl.obolibrary.org/obo/UBERON_
subontologies: {}
